name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # 메인 브랜치에 푸시될 때마다 실행됩니다.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # v2에서 v3으로 업데이트

      - name: Setup Node.js
        uses: actions/setup-node@v3  # v2에서 v3으로 업데이트
        with:
          node-version: '20'  # Node.js 버전을 14에서 20으로 업데이트

      - name: Install dependencies
        run: npm install

      - name: Install additional dependencies
        run: npm install --save-dev @babel/plugin-proposal-private-property-in-object typescript

      - name: Build the project
        run: npm run build

      - name: Create .nojekyll file
        run: echo > build/.nojekyll

      - name: Configure git for deployment
        run: |
          git config --global user.email "jaeminjeon123@gmail.com"
          git config --global user.name "jaeminjeon123"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          npm run deploy